//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoRandApplication.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int idEmployee { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime BirthDay { get; set; }
        public int idCashBox { get; set; }
        public int idTellPhone { get; set; }
        public int idStreet { get; set; }
    
        public virtual Abakan_Street Abakan_Street { get; set; }
        public virtual CashBox CashBox { get; set; }
        public virtual PhoneBook PhoneBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
