//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoRandApplication.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int idProduct { get; set; }
        public int idPart { get; set; }
        public short Qty { get; set; }
        public decimal Price { get; set; }
        public int idProvider { get; set; }
        public int idStore { get; set; }
        public int idTypePart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Part Part { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Store Store { get; set; }
        public virtual TypePart TypePart { get; set; }
    }
}
